### ISSUE TITLE
[bug]: DateTimePicker useEffect Loop, Browser Freeze

### ISSUE THREAD

**Issue by claudiograssia** [strapi/design-system#919] opened 2023-03-10 08:22 UTC
### What version of strapi-design-system are you using?

- Npm Version: 8.11.0
- Node Version: 16.16.0
- Strapi Design System Version: 1.6.3 / 1.6.5
- Browser Chrome

### What's Wrong?

In DateTimePicker useEffect depends of dateValue in same time in line 94 setDateValue change always value and it causing a loop in the useEffect and in next time browser freeze.
This occurs when datetime is already filled 

### To Reproduce

In Strapi:

1. Start Strapi in watch-admin in order the see the error on console
2. Create Collection with some field and also datetime
3. Create entry in this collection
4. Add Datetime without 00 time
5. Refresh browser in the edit entry
6. After some minute, browser stop working
7. In the console you can see the loop of stack

### Expected Behaviour

1. The espected behavior should not freeze the browser.
2. useEffect in DateTime should not setDateValue in position 94 for avoid the loop

**Comment by joshuaellis** [comment] 2023-03-10 08:43
Thanks for the report! This is actually a duplicate of #867 so I'm going to close this in favour of that.

**Closed by joshuaellis** 2023-03-10 08:43 UTC
Labels: status: duplicate
