### ISSUE TITLE
[feat]: Add placeholder to SubNavHeader

### ISSUE THREAD

**Issue by leoonsy** [strapi/design-system#1151] opened 2023-06-21 15:07 UTC
### A clear and concise description of what the feature is

Please add placeholder to SubNavHeader component. I can't remove 'e.g: strapi-plugin-abcd'. Thanks

### Why should this feature be included?

our team needs to change the default placeholder 

### Please provide an example for how this would work

`<SubNavHeader placeholder="my-placeholder"></SubNavHeader>`

**Comment by gu-stav** [comment] 2023-08-09 06:23
Closing as duplicate of https://github.com/strapi/design-system/issues/1201

**Closed by gu-stav** 2023-08-09 06:23 UTC
Labels: issue: enhancement
