### ISSUE TITLE
MenuItem as Link component does not support external links

### ISSUE THREAD

**Issue by HichamELBSI** [strapi/design-system#661] opened 2022-07-25 11:59 UTC
### Required System information

- Npm version: 8.5.0
- NodeJS version: 16.4.2
- Strapi Design System version: 1.2.0
- Browser: Chrome

### Describe the bug

The MenuItem component support internal links but not externals.

### Steps to reproduce the behavior

1. Use the SimpleMenu and MenuItem components
2. Try to add a href/isExternal props to use the MenuItem component as an external link.

**Comment by INNOVATIVEGAMER** [comment] 2022-10-05 19:39
hey @joshuaellis Can you please assign this to me?
Also, I think it's an enhancement and not a bug since this will add external link support to the current "MenuItem" component.

Tasks =>
1. Add support for external links to "MenuItem" component.
2. Add/Update documentation for the same in storybook
3. Add test cases to test the working of the external link

**Comment by joshuaellis** [comment] 2022-10-06 08:47
Hey @INNOVATIVEGAMER 

Tasks sound good, I'd probably remove the ternary operator for an `if` statement and look for the `isExternal` prop to know if it should be an anchor.

**Closed** 2022-12-19 08:34 UTC
Labels: issue: bug
