### ISSUE TITLE
[bug]: Datetimepicker slows down UI

### ISSUE THREAD

**Issue by Martijn-Schoenmaker-Webbio** [strapi/design-system#1244] opened 2023-08-02 08:27 UTC
### What version of strapi-design-system are you using?

NPM version: 8.19.2
Node.js version: 18.21.1
Strapi version: 4.12.0
Design system version: 1.8.2
Browser: Chrome

### What's Wrong?

When using the DateTimePicker as a plugin, it will cause a lot of slow down.

### To Reproduce

Inject a custom component that holds a DateTimePicker. In our case we injected it in the editView. It will slow down the typing in other fields significantly. 

Also using the DateTimePicker as a normal component inside a collectiontype (via de content type builder) will have its issues. When quickly changing from date to time, it can hog up the memory and crash the page --> https://share.getcloudapp.com/2Nup9D5X. It creates an infinite loop: https://share.getcloudapp.com/6quJXn2E

### Expected Behaviour

I wouldn't expect the DateTimePicker to crash or slow down the rest of the page.

**Comment by joshuaellis** [comment] 2023-08-07 07:14
It's hard to determine the cause of this bug without a reproduction, therefore i must insist one can be provided so we can accurately review this :)

**Comment by joshuaellis** [comment] 2023-08-07 09:08
So this is a duplicate issue then? In this case, i will close this issue in favour of the former :)

**Closed by joshuaellis** 2023-08-07 09:08 UTC
Labels: issue: bug, severity: low, status: can not reproduce, source: design-system

**Comment by Martijn-Schoenmaker-Webbio** [comment] 2023-08-07 09:27
I think it is. It however doesn't describe the use of the datepicker in de editView, which will slow down the input fields immensely.
